MOCK_DIR=$(top_builddir)/src/test/unit/mock
CMOCKERY_DIR=$(top_builddir)/src/test/unit/cmockery
CMOCKERY_OBJS=$(CMOCKERY_DIR)/cmockery.o
override CFLAGS+= -w $(PTHREAD_CFLAGS)

override CPPFLAGS+= -I$(CMOCKERY_DIR)

$(MOCK_DIR)/%_mock.c: $(abs_top_srcdir)/src/%.c
	@echo mocking $<
	PYTHONPATH=$(python_libdir) $(MOCK_DIR)/mocker.py $<

# For some reason, mock.o files are intermediate files sometimes.
# Mark them as secondary in order not to be deleted automatically.
.SECONDARY:
$(MOCK_DIR)/%_mock.o: $(MOCK_DIR)/%_mock.c

all: $(patsubst %,%.t,$(TARGETS)) $(patsubst %,%.green,$(CGREEN_TARGETS))

.PHONY:
check: $(patsubst %,%-check,$(TARGETS)) $(patsubst %,%-cgreen-check,$(CGREEN_TARGETS))

.PHONY:
%-check: %.t
	./$*.t
	
.PHONY:
%-cgreen-check: %.green
	LD_LIBRARY_PATH=/usr/local/lib ./$*.green

.PHONY:
clean: $(patsubst %,%-clean,$(TARGETS)) $(patsubst %,%-clean,$(CGREEN_TARGETS))

.PHONY:
%-clean:
	rm -f $*.t $*_test.o $*.green
